POST http://localhost:8081/api/post/create
Content-Type: application/json

{
  "userId": 5,
  "courseId": 3,
  "title": "测试人员的自我修养",
  "postTime": "2021-07-10T00:40:00.000Z",
  "content": "1.学会熬夜"
}

###{
#  "code": 1,
#  "msg": "操作成功",
#  "data": null
#}

GET http://localhost:8081/api/post/search/course/3/1/2

###{
#  "pageNum": 1,
#  "pageSize": 2,
#  "size": 2,
#  "startRow": 1,
#  "endRow": 2,
#  "total": 3,
#  "pages": 2,
#  "list": [
#    {
#      "postId": 10,
#      "courseId": 3,
#      "userId": 5,
#      "postTitle": "测试人员的自我修养",
#      "postContent": "1.1.1学会熬夜",
#      "postTime": "2021-07-15 07:40:00"
#    },
#    {
#      "postId": 9,
#      "courseId": 3,
#      "userId": 5,
#      "postTitle": "测试人员的自我修养",
#      "postContent": "1.1学会熬夜",
#      "postTime": "2021-07-10 14:02:00"
#    }
#  ],
#  "prePage": 0,
#  "nextPage": 2,
#  "isFirstPage": true,
#  "isLastPage": false,
#  "hasPreviousPage": false,
#  "hasNextPage": true,
#  "navigatePages": 8,
#  "navigatepageNums": [
#    1,
#    2
#  ],
#  "navigateFirstPage": 1,
#  "navigateLastPage": 2,
#  "lastPage": 2,
#  "firstPage": 1
#}
#

POST http://localhost:8081/api/post/delete
Content-Type: application/json

{
  "postId": 12
}

###{
#  "code": 1,
#  "msg": "操作成功",
#  "data": null
#}

POST http://localhost:8081/api/post/reply/create
Content-Type: application/json

{
  "postId": 13,
  "replyUserId": 4,
  "repliedUserId": 5,
  "replyContent": "2.学会使用工具",
  "replyTime": "2021-07-12T04:44:33.000Z"
}

###{
#  "code": 1,
#  "msg": "操作成功",
#  "data": null
#}

POST http://localhost:8081/api/post/reply_reply/create
Content-Type: application/json

{
  "replyUserId": 1,
  "repliedUserId": 2,
  "repliedId": 18,
  "replyContent": "5.遇到困难睡大觉",
  "replyTime": "2021-07-12T07:44:33.000Z"
}

###{
#  "code": 1,
#  "msg": "操作成功",
#  "data": null
#}


POST http://localhost:8081/api/post/search/post/1/2?userId=1&postId=8

###{
#  "pageNum": 1,
#  "pageSize": 2,
#  "size": 2,
#  "startRow": 1,
#  "endRow": 2,
#  "total": 4,
#  "pages": 2,
#  "list": [
#    {
#      "replyId": 10,
#      "postId": 8,
#      "replyUserId": 4,
#      "repliedUserId": 0,
#      "replyContent": "2.学会使用工具",
#      "repliedId": 0,
#      "replyTime": "2021-07-11 16:00:00",
#      "status": 0,
#      "newReplyNum": 0,
#      "newReplyList": null
#    },
#    {
#      "replyId": 11,
#      "postId": 8,
#      "replyUserId": 3,
#      "repliedUserId": 0,
#      "replyContent": "2.2学会使用工具",
#      "repliedId": 0,
#      "replyTime": "2021-07-11 16:00:00",
#      "status": 0,
#      "newReplyNum": 0,
#      "newReplyList": null
#    }
#  ],
#  "prePage": 0,
#  "nextPage": 2,
#  "isFirstPage": true,
#  "isLastPage": false,
#  "hasPreviousPage": false,
#  "hasNextPage": true,
#  "navigatePages": 8,
#  "navigatepageNums": [
#    1,
#    2
#  ],
#  "navigateFirstPage": 1,
#  "navigateLastPage": 2,
#  "firstPage": 1,
#  "lastPage": 2
#}
#

POST http://localhost:8081/api/post/search/post/1/2?userId=5&postId=8

###{
#  "pageNum": 1,
#  "pageSize": 2,
#  "size": 2,
#  "startRow": 1,
#  "endRow": 2,
#  "total": 4,
#  "pages": 2,
#  "list": [
#    {
#      "replyId": 10,
#      "postId": 8,
#      "replyUserId": 4,
#      "repliedUserId": 0,
#      "replyContent": "2.学会使用工具",
#      "repliedId": 0,
#      "replyTime": "2021-07-11 16:00:00",
#      "status": 0,
#      "newReplyNum": 0,
#      "newReplyList": null
#    },
#    {
#      "replyId": 11,
#      "postId": 8,
#      "replyUserId": 3,
#      "repliedUserId": 0,
#      "replyContent": "2.2学会使用工具",
#      "repliedId": 0,
#      "replyTime": "2021-07-11 16:00:00",
#      "status": 0,
#      "newReplyNum": 0,
#      "newReplyList": null
#    }
#  ],
#  "prePage": 0,
#  "nextPage": 2,
#  "isFirstPage": true,
#  "isLastPage": false,
#  "hasPreviousPage": false,
#  "hasNextPage": true,
#  "navigatePages": 8,
#  "navigatepageNums": [
#    1,
#    2
#  ],
#  "navigateFirstPage": 1,
#  "navigateLastPage": 2,
#  "firstPage": 1,
#  "lastPage": 2
#}
#

POST http://localhost:8081/api/post/search/reply/1/2?userId=1&repliedId=10

###{
#  "pageNum": 1,
#  "pageSize": 2,
#  "size": 2,
#  "startRow": 1,
#  "endRow": 2,
#  "total": 3,
#  "pages": 2,
#  "list": [
#    {
#      "replyId": 14,
#      "postId": null,
#      "replyUserId": 1,
#      "repliedUserId": 4,
#      "replyContent": "3.学会debug",
#      "repliedId": 10,
#      "replyTime": "2021-07-11 16:00:00",
#      "status": 0,
#      "newReplyNum": null,
#      "newReplyList": null
#    },
#    {
#      "replyId": 15,
#      "postId": null,
#      "replyUserId": 2,
#      "repliedUserId": 4,
#      "replyContent": "3.3.学会debug",
#      "repliedId": 10,
#      "replyTime": "2021-07-11 16:00:00",
#      "status": 0,
#      "newReplyNum": null,
#      "newReplyList": null
#    }
#  ],
#  "prePage": 0,
#  "nextPage": 2,
#  "isFirstPage": true,
#  "isLastPage": false,
#  "hasPreviousPage": false,
#  "hasNextPage": true,
#  "navigatePages": 8,
#  "navigatepageNums": [
#    1,
#    2
#  ],
#  "navigateFirstPage": 1,
#  "navigateLastPage": 2,
#  "firstPage": 1,
#  "lastPage": 2
#}
#

POST http://localhost:8081/api/post/search/reply/1/3?userId=3&repliedId=16
###{
#  "pageNum": 1,
#  "pageSize": 3,
#  "size": 2,
#  "startRow": 1,
#  "endRow": 2,
#  "total": 2,
#  "pages": 1,
#  "list": [
#    {
#      "replyId": 17,
#      "postId": null,
#      "replyUserId": 1,
#      "repliedUserId": 3,
#      "replyContent": "4.学会放弃",
#      "repliedId": 16,
#      "replyTime": "2021-07-11 16:00:00",
#      "status": 0,
#      "newReplyNum": null,
#      "newReplyList": null
#    },
#    {
#      "replyId": 18,
#      "postId": null,
#      "replyUserId": 2,
#      "repliedUserId": 3,
#      "replyContent": "4.4.学会放弃",
#      "repliedId": 16,
#      "replyTime": "2021-07-11 16:00:00",
#      "status": 0,
#      "newReplyNum": null,
#      "newReplyList": null
#    }
#  ],
#  "prePage": 0,
#  "nextPage": 0,
#  "isFirstPage": true,
#  "isLastPage": true,
#  "hasPreviousPage": false,
#  "hasNextPage": false,
#  "navigatePages": 8,
#  "navigatepageNums": [
#    1
#  ],
#  "navigateFirstPage": 1,
#  "navigateLastPage": 1,
#  "lastPage": 1,
#  "firstPage": 1
#}
#

GET http://localhost:8081/api/post/search/userPost/1/5?userId=5

###{
#  "pageNum": 1,
#  "pageSize": 5,
#  "size": 5,
#  "startRow": 1,
#  "endRow": 5,
#  "total": 5,
#  "pages": 1,
#  "list": [
#    {
#      "postId": 8,
#      "courseId": 3,
#      "userId": 5,
#      "postTitle": "测试人员的自我修养",
#      "postContent": "1.学会熬夜",
#      "postTime": "2021-07-10 00:40:00",
#      "newReplyNum": 2,
#      "newReplyList": [
#        12,
#        13
#      ]
#    },
#    {
#      "postId": 9,
#      "courseId": 3,
#      "userId": 5,
#      "postTitle": "测试人员的自我修养",
#      "postContent": "1.1学会熬夜",
#      "postTime": "2021-07-10 06:02:00",
#      "newReplyNum": 0,
#      "newReplyList": []
#    },
#    {
#      "postId": 10,
#      "courseId": 3,
#      "userId": 5,
#      "postTitle": "测试人员的自我修养",
#      "postContent": "1.1.1学会熬夜",
#      "postTime": "2021-07-14 23:40:00",
#      "newReplyNum": 0,
#      "newReplyList": []
#    },
#    {
#      "postId": 11,
#      "courseId": 3,
#      "userId": 5,
#      "postTitle": "测试人员的自我修养",
#      "postContent": "2.学会熬夜",
#      "postTime": "2021-07-10 00:40:00",
#      "newReplyNum": 0,
#      "newReplyList": []
#    },
#    {
#      "postId": 13,
#      "courseId": 3,
#      "userId": 5,
#      "postTitle": "测试人员的自我修养",
#      "postContent": "3.学会熬夜",
#      "postTime": "2021-07-10 00:40:00",
#      "newReplyNum": 0,
#      "newReplyList": []
#    }
#  ],
#  "prePage": 0,
#  "nextPage": 0,
#  "isFirstPage": true,
#  "isLastPage": true,
#  "hasPreviousPage": false,
#  "hasNextPage": false,
#  "navigatePages": 8,
#  "navigatepageNums": [
#    1
#  ],
#  "navigateFirstPage": 1,
#  "navigateLastPage": 1,
#  "lastPage": 1,
#  "firstPage": 1
#}

GET http://localhost:8081/api/post/search/userReply/1/5?userId=4

###{
#  "pageNum": 1,
#  "pageSize": 5,
#  "size": 1,
#  "startRow": 1,
#  "endRow": 1,
#  "total": 1,
#  "pages": 1,
#  "list": [
#    {
#      "replyId": 10,
#      "postId": 8,
#      "replyUserId": 4,
#      "repliedUserId": 0,
#      "replyContent": "2.学会使用工具",
#      "repliedId": null,
#      "replyTime": "2021-07-11 16:00:00",
#      "status": 1,
#      "newReplyNum": 3,
#      "newReplyList": [
#        14,
#        15,
#        16
#      ]
#    }
#  ],
#  "prePage": 0,
#  "nextPage": 0,
#  "isFirstPage": true,
#  "isLastPage": true,
#  "hasPreviousPage": false,
#  "hasNextPage": false,
#  "navigatePages": 8,
#  "navigatepageNums": [
#    1
#  ],
#  "navigateFirstPage": 1,
#  "navigateLastPage": 1,
#  "lastPage": 1,
#  "firstPage": 1
#}

POST http://localhost:8081/api/post/search/newReply/1/2?replyIdList=14,15,16

###{
#  "pageNum": 1,
#  "pageSize": 2,
#  "size": 2,
#  "startRow": 0,
#  "endRow": 2,
#  "total": 3,
#  "pages": 2,
#  "list": [
#    {
#      "replyId": 14,
#      "postId": null,
#      "replyUserId": 1,
#      "repliedUserId": 4,
#      "replyContent": "3.学会debug",
#      "repliedId": 10,
#      "replyTime": "2021-07-11 16:00:00",
#      "status": 0,
#      "newReplyNum": null,
#      "newReplyList": null
#    },
#    {
#      "replyId": 15,
#      "postId": null,
#      "replyUserId": 2,
#      "repliedUserId": 4,
#      "replyContent": "3.3.学会debug",
#      "repliedId": 10,
#      "replyTime": "2021-07-11 16:00:00",
#      "status": 0,
#      "newReplyNum": null,
#      "newReplyList": null
#    }
#  ],
#  "prePage": 0,
#  "nextPage": 2,
#  "isFirstPage": true,
#  "isLastPage": false,
#  "hasPreviousPage": false,
#  "hasNextPage": true,
#  "navigatePages": 8,
#  "navigatepageNums": [
#    1,
#    0
#  ],
#  "navigateFirstPage": 1,
#  "navigateLastPage": 2,
#  "lastPage": 2,
#  "firstPage": 1
#}
#
#Response code: 200; Time: 371ms; Content length: 687 bytes
POST http://localhost:8081/api/post/delete
Content-Type: application/json

{
  "postId": 8
}